### ISSUE TITLE
vimL function must not be called in a lua loop callback

### ISSUE THREAD

**Issue by guzman109** [amitds1997/remote-nvim.nvim#52] opened 2023-09-27 22:46 UTC
I'm new to Neovim and Lazy.vim as well. I just installed the plugin and try to run it and was met with this error.

 .local/share/nvim/lazy/remote-nvim.nvim/lua/remote-nvim/providers/provider.lua:418: /usr/share/nvim/runtime/lua/vim/ui.lua:50: E5560: vimL function must not be called in a lua loop callback

**To Reproduce**
1. :Lazy load remote-nvim.nvim
2. :RemoteStart
3. Select from ssh config file

**Expected behavior**
Expected to connect to server

**System Info**
* Your local OS: Ubuntu 23.04 
* Local Neovim version: 0.9.2
* Remote host OS (if applicable): Rocky Linux
* Remote Neovim version (if applicable): None. Do I need it installed on the server?

**Comment by amitds1997** [comment] 2023-09-28 06:12
Thanks for reporting this! And welcome to the Neovim community!!

I was able to find the root cause of this and pushed out a fix for this. It should backport into the release in a couple of minutes which should fix this for you. Feel free to comment here in case you still see it.

**Closed** 2023-09-28 06:12 UTC
