### ISSUE TITLE
Non-standard config path in local

### ISSUE THREAD

**Issue by knmac** [amitds1997/remote-nvim.nvim#137] opened 2024-05-25 21:35 UTC
**Is your feature request related to a problem? Please describe.**
Having a non-standard config path in local machine prevents loading the config on remote. For example, if the path to the config is `~/.config/weird_nvim/`, then after copying the config over, there will be two directories on remote:
- `~/.remote-nvim/workspaces/[workspace_tag]/.config/weird_nvim/`, this is the copied config folder from local, and
- `~/.remote-nvim/workspaces/[workspace_tag]/.config/nvim/`, this is the **empty** default config folder. Remote-nvim will load from this instead of the other folder.

**Describe the solution you'd like**
Specifying with remote config folder to load. This is similar to `NVIM_APPNAME`. For example,
```lua
copy_dirs = {
  config = {
    base = vim.fn.stdpath("config"),
    dirs = "*",
    nvim_appname = "weird_nvim",
  }
}
```

**Comment by amitds1997** [comment] 2024-05-26 02:35
Thanks for reporting this! I am able to reproduce the issue. Will push out a fix soon.

**Comment by amitds1997** [comment] 2024-05-26 02:58
Hey, I pushed out a fix and released it in [v0.3.9](https://github.com/amitds1997/remote-nvim.nvim/releases/tag/v0.3.9). Let me know if you are able to work with it now.

Your updated configuration should look like:
```lua
remote = {
    app_name = "weird-nvim",
    -- List of directories that should be copied over
    copy_dirs = {
      config = {
        base = "<path-to-weird-nvim>",
      }
    }
```

The structure is so because [`NVIM_APPNAME`](https://neovim.io/doc/user/starting.html#%24NVIM_APPNAME) overrides all `XDG_CONFIG_*` paths. If you still see this issue, let me know. Thanks!

**Comment by knmac** [comment] 2024-05-26 05:23
It seems if sub-dirs are specified, they are not copied to the correct path on remote? For example, the following config
```lua
remote = {
    app_name = "weird-nvim",
    copy_dirs = {
      config = {
        base = "<path-to-weird-nvim>",
        dirs = {"lonely-dir"},
      }
    }
```
would result in an empty `~/.remote-nvim/workspaces/[workspace_tag]/.config/weird-nvim/` and `~/.remote-nvim/workspaces/[workspace_tag]/.config/lonely-dir/`, while the `lonely-dir` is expected to be inside `weird-nvim/`.

**Comment by amitds1997** [comment] 2024-05-26 06:36
Sorry, did not see your message come in. Was able to reproduce this. I would implement and push the fix in the next couple of hours. The earlier fix broke this behavior apparently 😢

**Comment by amitds1997** [comment] 2024-06-08 08:41
Hi, thanks for being patient. I merged a fix so both the scenarios work Ok now. Let me know if you still see any issues.

**Closed** 2024-06-08 08:40 UTC

**Comment by knmac** [comment] 2024-06-10 16:33
That looks great! Thank you!
